update

diff --git a/.github/workflows/Debug.yaml b/.github/workflows/Debug.yaml
--- a/.github/workflows/Debug.yaml
+++ b/.github/workflows/Debug.yaml
@@ -13,35 +13,19 @@ jobs:
         id: clean_old_run
         env:
           GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
-          API_URL: https://api.github.com
-          CANCEL_RUN: false
+          GITHUB_API_URL: https://api.github.com
         run: |
           API_URL=${GITHUB_API_URL:-"https://api.github.com"}
-
           WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
-
           gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
-            | jq -r '.workflow_runs[] | {id: .id, status: .status}' \
-            | while read -r RUN; do
-                RUN_ID=$(echo "$RUN" | jq -r '.id')
-                STATUS=$(echo "$RUN" | jq -r '.status')
-
-                # Cancel running workflows if CANCEL_RUN is true
-                if [[ "$STATUS" == "in_progress" && "${CANCEL_RUN}" == "true" ]]; then
-                    echo "Canceling workflow run ID: $RUN_ID"
-                    if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
-                        echo "Successfully canceled workflow run ID: $RUN_ID"
-                    else
-                        echo "Failed to cancel workflow run ID: $RUN_ID"
-                        continue
-                    fi
-                fi
-
-                # Delete the workflow run
-                echo "Deleting workflow run ID: $RUN_ID (Status: $STATUS)"
-                if gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}"; then
-                    echo "Deleted workflow run ID: $RUN_ID"
-                else
-                    echo "Failed to delete workflow run ID: $RUN_ID"
-                fi
+            | jq -r '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | .id' \
+            | while read -r RUN_ID; do
+                echo "Deleting workflow run ID: $RUN_ID"
+                gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
+                echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
             done
+
+      - name: Clean up disk
+        id: clean_disk
+        run: |
+          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
