update

diff --git a/.github/workflows/Debug.yaml b/.github/workflows/Debug.yaml
--- a/.github/workflows/Debug.yaml
+++ b/.github/workflows/Debug.yaml
@@ -9,34 +9,34 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      # - name: Clean old run log
-      #   id: clean_old_run
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
-      #     GITHUB_API_URL: https://api.github.com
-      #   run: |
-      #     export
-      #     API_URL=${GITHUB_API_URL:-"https://api.github.com"}
-      #     WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
+      - name: Clean old run log
+        id: clean_old_run
+        env:
+          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
+          GITHUB_API_URL: https://api.github.com
+        run: |
+          export
+          API_URL=${GITHUB_API_URL:-"https://api.github.com"}
+          WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
 
-      #     gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
-      #       | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber) and (.status == "in_progress" or .status == "queued")) | .id' \
-      #       | while read -r RUN_ID; do
-      #           echo "Cancelling workflow run ID: $RUN_ID"
-      #           if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
-      #             echo "Successfully cancelled workflow run ID: $RUN_ID"
-      #           else
-      #             echo "Failed to cancel workflow run ID: $RUN_ID"
-      #           fi
-      #       done
+          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber) and (.status == "in_progress" or .status == "queued")) | .id' \
+            | while read -r RUN_ID; do
+                echo "Cancelling workflow run ID: $RUN_ID"
+                if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
+                  echo "Successfully cancelled workflow run ID: $RUN_ID"
+                else
+                  echo "Failed to cancel workflow run ID: $RUN_ID"
+                fi
+            done
 
-      #     gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
-      #       | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber)) | .id' \
-      #       | while read -r RUN_ID; do
-      #           echo "Deleting workflow run ID: $RUN_ID"
-      #           gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
-      #           echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
-      #       done
+          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber)) | .id' \
+            | while read -r RUN_ID; do
+                echo "Deleting workflow run ID: $RUN_ID"
+                gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
+                echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
+            done
 
       # - name: Clean up disk
       #   id: clean_disk
