update

diff --git a/.github/workflows/Debug.yaml b/.github/workflows/Debug.yaml
--- a/.github/workflows/Debug.yaml
+++ b/.github/workflows/Debug.yaml
@@ -18,14 +18,25 @@ jobs:
           export
           API_URL=${GITHUB_API_URL:-"https://api.github.com"}
           WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
-          gh api "/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
-            | jq -c '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | {id: .id, status: .status, conclusion: .conclusion}' \
-            | while read -r RUN; do
-                RUN_ID=$(echo "$RUN" | jq -r '.id')
-                STATUS=$(echo "$RUN" | jq -r '.status')
-                CONCLUSION=$(echo "$RUN" | jq -r '.conclusion')
-                echo "$RUN_ID $STATUS $CONCLUSION"
+
+          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+            | jq -r '.workflow_runs[] | select(.id != $GITHUB_RUN_ID and .status == "in_progress" or .status == "queued") | .id' \
+            | while read -r RUN_ID; do
+                echo "Cancelling workflow run ID: $RUN_ID"
+                if gh api -X POST "/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
+                  echo "Successfully cancelled workflow run ID: $RUN_ID"
+                else
+                  echo "Failed to cancel workflow run ID: $RUN_ID"
+                fi
             done
+
+          # gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+          #   | jq -r '.workflow_runs[] | select(.id != $GITHUB_RUN_ID) | .id' \
+          #   | while read -r RUN_ID; do
+          #       echo "Deleting workflow run ID: $RUN_ID"
+          #       gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
+          #       echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
+          #   done
 
       - name: Clean up disk
         id: clean_disk
