update

diff --git a/.github/workflows/Deploy.yaml b/.github/workflows/Deploy.yaml
--- a/.github/workflows/Deploy.yaml
+++ b/.github/workflows/Deploy.yaml
@@ -9,7 +9,6 @@ jobs:
     steps:
       - name: Check Build Success and Proceed Conditionally
         run: |
-          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
           if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
             echo "Build was successful,start the deploy."
             echo "DEPLOY=true" >> $GITHUB_OUTPUT
@@ -23,13 +22,39 @@ jobs:
           fi
         id: check_success
 
-      - uses: actions/checkout@v4
+      - name: Clean old run log
+        id: clean_old_run
+        env:
+          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
+          GITHUB_API_URL: https://api.github.com
+        run: |
+          export
+          API_URL=${GITHUB_API_URL:-"https://api.github.com"}
+          WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
 
-      - name: Cleanup previous logs
-        uses: ./.github/actions/clean-old-run
-        with:
-          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
-          cancel_run: ${{ steps.check_success.outputs.DEPLOY }}
+          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber) and (.status == "in_progress" or .status == "queued")) | .id' \
+            | while read -r RUN_ID; do
+                echo "Cancelling workflow run ID: $RUN_ID"
+                if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
+                  echo "Successfully cancelled workflow run ID: $RUN_ID"
+                else
+                  echo "Failed to cancel workflow run ID: $RUN_ID"
+                fi
+            done
+
+          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
+            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber)) | .id' \
+            | while read -r RUN_ID; do
+                echo "Deleting workflow run ID: $RUN_ID"
+                gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
+                echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
+            done
+
+      - name: Clean up disk
+        id: clean_disk
+        run: |
+          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
@@ -37,13 +62,15 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Deploy
+      - uses: actions/checkout@v4
+
+      - name: Deploy compose
         if: steps.check_success.outputs.DEPLOY == 'true'
         env:
-          REPO_URL: https://github.com/ratata1590hcm/ProjectTemplate
+          REPO_URL: ${{ secrets.GH_REPO }}
           GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
         uses: ./.github/actions/compose
         with:
-          base_path: Example
+          base_path: compose
           scan: false
           skip_composedown: true
